interface ILocalizedStrings {
  appName: string;
  settingsScreen: string;
  pushMe: string;
  onPress: string;
  aboutScreen: string;
  like: string;
  dictionaryPlaceholder: string;
  continue: string;
  addDictionary: string;
  editDictionary: string;
  successAddedDictionary: string;
  errorEmptyDictionary: string;
  successEditDictionary: string;
  errorEmptyThemeWords: string;
  successAddedThemeWords: string;
  addThemeWords: string;
  editThemeWords: string;
  themeWordsPlaceholder: string;
  successEditThemeWords: string;
  addThemeTitleBtn: string;
  addWord: string;
  editWord: string;
  emptyWordsList: string;
  validationWordMax: string;
  requiredTranslate: string;
  requiredForeign: string;
  foreignWord: string;
  translateWord: string;
  transcriptionWord: string;
  editWordToast: string;
  addWordToast: string;
  allWords: string;
  learnedWords: string;
  unlearnedWords: string;
  version: string;
  createdBy: string;
  noWordsForStudying: string;
  isSuggestTranscriptKeyboard: string;
  suggest: string;
  voiceLanguage: string;
  chooseVoiceLanguage: string;
}

export default ILocalizedStrings;
