export enum RouteScreensEnum {
  MainScreen = 'MainScreen',
  SettingsScreen='SettingsScreen',
  AboutScreen = 'AboutScreen',
  DictionaryCreateScreen = 'DictionaryCreateScreen',
  DictionaryEditScreen = 'DictionaryEditScreen',
  ThemeWordsCreateScreen = 'ThemeWordsCreateScreen',
  ThemeWordsEditScreen = 'ThemeWordsEditScreen',
  WordCreateScreen = 'WordCreateScreen',
  WordEditScreen = 'WordEditScreen',
  ListWordsScreen = 'ListWordsScreen',
  RepeatWordScreen = 'RepeatWordScreen',
  SelectWordScreen = 'SelectWordScreen',
  WriteWordScreen = 'WriteWordScreen',
}
