import Dictionary from './models/Dictionary';
import ThemeOfWords from './models/ThemeOfWords';

export const mockDictionary: Dictionary[] = [
  {
    id: 1,
    name: 'English',
    percentOfLearned: 20,
  },
  {
    id:2,
    name: 'Esperanto',
    percentOfLearned: 0,
  },
  {
    id:3,
    name: 'Марсианское наречие',
    percentOfLearned: 49,
  },
];


export const mockThemes: ThemeOfWords[] = [
  {
    id: 1,
    name: 'Дом',
    idDictionary: 1,
    percentOfLearned: 25,
    lastUpdate: new Date(),
    isBeginLearned: true,
  },
  {
    id: 2,
    name: 'Аэропорт',
    idDictionary: 1,
    percentOfLearned: 0,
    lastUpdate: new Date(),
    isBeginLearned: false,
  },
  {
    id: 3,
    name: 'Тело человека',
    idDictionary: 1,
    percentOfLearned: 25,
    lastUpdate: new Date(),
    isBeginLearned: true,
  },
  {
    id: 4,
    name: 'Популярные',
    idDictionary: 2,
    percentOfLearned: 30,
    lastUpdate: new Date(),
    isBeginLearned: true,
  },
  {
    id: 5,
    name: 'Как пройти',
    idDictionary: 2,
    percentOfLearned: 87,
    lastUpdate: new Date(),
    isBeginLearned: false,
  },
  {
    id: 6,
    name: 'Путешествие',
    idDictionary: 2,
    percentOfLearned: 15,
    lastUpdate: new Date(),
    isBeginLearned: true,
  },

  {
    id: 7,
    name: 'Автомобиль',
    idDictionary: 2,
    percentOfLearned: 30,
    lastUpdate: new Date(),
    isBeginLearned: true,
  },
  {
    id: 8,
    name: 'Космос',
    idDictionary: 2,
    percentOfLearned: 87,
    lastUpdate: new Date(),
    isBeginLearned: false,
  },
  {
    id: 9,
    name: 'Корабль',
    idDictionary: 2,
    percentOfLearned: 15,
    lastUpdate: new Date(),
    isBeginLearned: true,
  },


  {
    id: 10,
    name: 'Животные',
    idDictionary: 2,
    percentOfLearned: 30,
    lastUpdate: new Date(),
    isBeginLearned: true,
  },
  {
    id: 11,
    name: 'Строение человека',
    idDictionary: 2,
    percentOfLearned: 87,
    lastUpdate: new Date(),
    isBeginLearned: false,
  },
  {
    id: 12,
    name: 'Кухня',
    idDictionary: 2,
    percentOfLearned: 15,
    lastUpdate: new Date(),
    isBeginLearned: true,
  },

  {
    id: 13,
    name: 'Ресторан',
    idDictionary: 2,
    percentOfLearned: 30,
    lastUpdate: new Date(),
    isBeginLearned: true,
  },
  {
    id: 14,
    name: 'Ванная',
    idDictionary: 2,
    percentOfLearned: 87,
    lastUpdate: new Date(),
    isBeginLearned: false,
  },
  {
    id: 15,
    name: 'Квартира',
    idDictionary: 2,
    percentOfLearned: 15,
    lastUpdate: new Date(),
    isBeginLearned: true,
  },
  {
    id: 7,
    name: 'Популярные',
    idDictionary: 3,
    percentOfLearned: 10,
    lastUpdate: new Date(),
    isBeginLearned: true,
  },
  {
    id: 8,
    name: 'Автвокзал',
    idDictionary: 3,
    percentOfLearned: 0,
    lastUpdate: new Date(),
    isBeginLearned: false,
  },
  {
    id: 9,
    name: 'Аэропорт',
    idDictionary: 3,
    percentOfLearned: 0,
    lastUpdate: new Date(),
    isBeginLearned: true,
  },
  {
    id: 10,
    name: 'Работа',
    idDictionary: 3,
    percentOfLearned: 0,
    lastUpdate: new Date(),
    isBeginLearned: true,
  },
  {
    id: 11,
    name: 'Характер человека',
    idDictionary: 3,
    percentOfLearned: 0,
    lastUpdate: new Date(),
    isBeginLearned: true,
  },
];


export const mockWords = [
  {
    id: 1,
    idTheme: 1,
    foreign: 'book',
    translation: 'книга',
    transcription: '[boo:k]',
    isLearned: false,
  },
  {
    id: 2,
    idTheme: 1,
    foreign: 'adult',
    translation: 'взрослый',
    transcription: '[ˈædʌlt]',
    isLearned: false,
  },
  {
    id: 3,
    idTheme: 1,
    foreign: 'age',
    translation: 'возраст',
    transcription: '[eɪdʒ]',
    isLearned: false,
  },
  {
    id: 4,
    idTheme: 1,
    foreign: 'baby',
    translation: 'малыш',
    transcription: '[ˈbeɪbɪ]',
    isLearned: false,
  },
  {
    id: 5,
    idTheme: 1,
    foreign: 'birth',
    translation: 'рождение',
    transcription: '[bɜːθ]',
    isLearned: false,
  },
  {
    id: 6,
    idTheme: 1,
    foreign: 'boy',
    translation: 'мальчик',
    transcription: '[bɔɪ]',
    isLearned: false,
  },
  {
    id: 7,
    idTheme: 1,
    foreign: 'child',
    translation: 'ребенок',
    transcription: '[tʃaɪld]',
    isLearned: false,
  },
  {
    id: 8,
    idTheme: 1,
    foreign: 'childhood',
    translation: 'детство',
    transcription: '[ˈtʃaɪldhʊd]',
    isLearned: false,
  },
  {
    id: 9,
    idTheme: 1,
    foreign: 'girl',
    translation: 'девочка',
    transcription: '[ɡɜːl]',
    isLearned: false,
  },
  {
    id: 10,
    idTheme: 1,
    foreign: 'human',
    translation: 'человек',
    transcription: '[ˈhjuːmən]',
    isLearned: false,
  },
  {
    id: 11,
    idTheme: 1,
    foreign: 'life',
    translation: 'жизнь',
    transcription: '[laɪf]',
    isLearned: false,
  },
  {
    id: 12,
    idTheme: 1,
    foreign: 'man',
    translation: 'мужчина',
    transcription: '[mæn]',
    isLearned: false,
  },
    {
      id: 13,
      idTheme: 2,
      foreign: 'age',
      translation: 'возраст',
      transcription: '[eɪdʒ]',
      isLearned: false,
    },
  {
    id: 14,
    idTheme: 2,
    foreign: 'baby',
    translation: 'малыш',
    transcription: '[ˈbeɪbɪ]',
    isLearned: false,
  },
  {
    id: 15,
    idTheme: 2,
    foreign: 'birth',
    translation: 'рождение',
    transcription: '[bɜːθ]',
    isLearned: false,
  },
  {
    id: 16,
    idTheme: 2,
    foreign: 'boy',
    translation: 'мальчик',
    transcription: '[bɔɪ]',
    isLearned: false,
  },
  {
    id: 17,
    idTheme: 2,
    foreign: 'child',
    translation: 'ребенок',
    transcription: '[tʃaɪld]',
    isLearned: false,
  },
  {
    id: 18,
    idTheme: 2,
    foreign: 'childhood',
    translation: 'детство',
    transcription: '[ˈtʃaɪldhʊd]',
    isLearned: false,
  },
  {
    id: 19,
    idTheme: 2,
    foreign: 'girl',
    translation: 'девочка',
    transcription: '[ɡɜːl]',
    isLearned: false,
  },
  {
    id: 20,
    idTheme: 2,
    foreign: 'human',
    translation: 'человек',
    transcription: '[ˈhjuːmən]',
    isLearned: false,
  },
  {
    id: 21,
    idTheme: 2,
    foreign: 'life',
    translation: 'жизнь',
    transcription: '[laɪf]',
    isLearned: false,
  },
  {
    id: 22,
    idTheme: 2,
    foreign: 'man',
    translation: 'мужчина',
    transcription: '[mæn]',
    isLearned: false,
  },
];

